DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS carbon_conversion_factor;

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL
);

CREATE TABLE post (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  author_id INTEGER NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);

CREATE TABLE carbon_conversion_factor (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  display_name TEXT NOT NULL,
  api_name TEXT NOT NULL,
  input_units TEXT NOT NULL,
  input_to_co2 REAL NOT NULL,
  output_units TEXT NOT NULL,
  input_to_output REAL NOT NULL,
  required_flags TEXT DEFAULT NULL,
  required_flags_value REAL DEFAULT NULL
);
